old_sound_rabbit_mq:
    connections:
        default:
            host: '%env(RABBITMQ_HOSTNAME)%'
            #use_socket: true
    producers:
        # use 'old_sound_rabbit_mq.change_producer' service to send data.
        change:
            connection:       default
            exchange_options: { name: 'change', type: direct }
    consumers:
        change:
            connection:       default
            exchange_options: { name: 'change', type: direct }
            queue_options:    { name: 'change'}
            callback:         App\Consumer\ChangeConsumer
        exchange:
            connection:       default
            exchange_options: { name: 'exchange', type: direct }
            queue_options:    { name: 'exchange'}
            callback:         App\Consumer\ExchangeConsumer
        lock:
            connection:       default
            exchange_options: { name: 'lock', type: direct }
            queue_options:    { name: 'lock'}
            callback:         App\Consumer\LockConsumer
        unlock:
            connection:       default
            exchange_options: { name: 'unlock', type: direct }
            queue_options:    { name: 'unlock'}
            callback:         App\Consumer\UnlockConsumer
